######################################################################
# Automatically generated by qmake (3.0) Sun Sep 4 15:28:00 2016
######################################################################

TEMPLATE = app
TARGET = AIDoll
INCLUDEPATH += .
QT += core widgets

# Input
SOURCES += Main.cpp
