######################################################################
# Automatically generated by qmake (3.0) Sun Sep 4 15:28:00 2016
######################################################################

TEMPLATE = app
TARGET = AIDoll
INCLUDEPATH += .
QT += core widgets network

# Input
SOURCES += Main.cpp DollBody.cpp MessageView.cpp MessageReceiver.cpp DollSettings.cpp
HEADERS += DollBody.hpp MessageView.hpp MessageReceiver.hpp Message.hpp DollSettings.hpp
